[package]
name = "FortranCompiler"
version = "0.1.0"
edition = "2024"

[dependencies]
cranelift = "0.102"
cranelift-codegen = "0.102"
cranelift-frontend = "0.102"
cranelift-module = "0.102"
cranelift-object = "0.102"
target-lexicon = "0.12"
anyhow = "1.0"